# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Contacts' do
  use_frameworks!

  # Pods for Contacts
  pod 'Alamofire'
  target 'ContactsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
